version: '3'

services:

  redis:
    image: redis:5
    ports: 
      - "6379:6379"

  backend-drf:
    restart: unless-stopped
    build:
      context: ../../cryptocurrency-backend/
      dockerfile: deploy/Dockerfile-for-compose
    ports:
      - "8000:8000"
    depends_on:
      - redis
    links:
      - redis

  backend-chanel:
    restart: unless-stopped
    build:
      context: ../../cryptocurrency-backend/
      dockerfile: deploy/Dockerfile-async
    ports:
      - "8001:8001"
    depends_on:
      - redis
    links:
      - redis

  frontend-react:
    build: ../../cryptocurrency-frontend/
    restart: 'on-failure'
    command: ["npm", "start"]
    ports:
      - "3000:3000"