version: '3'

services:
  
  redis:
    image: redis:5
    ports: 
      - "6379:6379"

  django:
    build:
      context: ../../cryptocurrency-backend/
      dockerfile: deploy/Dockerfile-for-compose
    ports:
      - "8000:8000"
    depends_on:
      - redis
    restart: always

  frontend:
    build: ../../crypto-currency-frontend/
    command: ["npm", "start"]
    ports:
      - "3000:3000"

