# base image 
FROM python:3.8

MAINTAINER Andrew
ADD ./  /usr/src/app
WORKDIR /usr/src/app
COPY deploy/pip.txt ./
RUN pip install --no-cache-dir -r pip.txt
RUN python base_app/manage.py migrate
EXPOSE 8000
CMD exec gunicorn -w 3 -b 0.0.0.0:8000 --chdir base_app/ base_app.wsgi:application --reload
