# base image 
FROM python:3.8

MAINTAINER Andrew
ADD ./  /usr/src/app
WORKDIR /usr/src/app
COPY deploy/pip.txt ./
RUN pip install --no-cache-dir -r pip.txt
EXPOSE 8001
WORKDIR /usr/src/app/base_app
CMD exec daphne base_app.asgi:application --bind 0.0.0.0 --port 8001
