# Generated by Django 3.2 on 2021-04-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_auto_20210412_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='currency',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='currency',
            field=models.ManyToManyField(to='currency.Currency'),
        ),
    ]
