# Generated by Django 3.2 on 2021-05-12 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_auto_20210412_0949'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dashboard',
        ),
    ]
