# Generated by Django 3.2 on 2021-05-18 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('currency', '0006_delete_dashboard'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.account'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='currency',
            field=models.ManyToManyField(blank=True, to='currency.Currency'),
        ),
    ]
